FROM python:3

#FROM ubuntu:latest

#RUN apt-get update -y && apt-get install -y python-pip python3.5-dev build-essential libpq-dev && pip install tensorflow && pip install pytest && pip install pandas
RUN pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl
RUN pip install pytest pandas kaggle

