wordpress:
        image: wordpress:4.2.2
        links:
                - db:mysql
        expose:
                - 3000
        ports:
                - "0:3000"
                  #        ports:
                  #- 8080:80

db:
        image: mariadb
        environment:
                MYSQL_ROOT_PASSWORD: example
